name: sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: medz
      - id: changed
        run: |
          if [ -z "$(git status -s)"]; then
            echo "value=1" >> $GITHUB_OUTPUT
          else
            echo "value=" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.changed.outputs.value }}
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "chore: update sponsors [skip ci]" --all -s
          git push
